---
vms:
## puppet enterprise master
- name: master
  box: puppetlabs/centos-7.2-64-nocm
  private_networks: [ {ip: '10.20.1.10'} ]
  hostname: master.icingacampams.vm
  roles:
  - pe-puppet-master
## icinga server
- name: icinga2
  box: puppetlabs/centos-7.2-64-nocm
  private_networks: [ {ip: '10.20.1.20'} ]
  hostname: icinga2.icingacampams.vm
  roles:
  - pe-puppet-agent
- name: peclient
  box: puppetlabs/centos-7.2-64-nocm
  private_networks: [ {ip: '10.20.1.200'} ]
  hostname: peclient.icingacampams.vm
  roles:
  - pe-puppet-agent
- name: icingacampams
  box: puppetlabs/centos-7.2-64-nocm
  private_networks: [ {ip: '10.20.1.201'} ]
  hostname: icingacampams.icingacampams.vm
  roles:
  - pe-puppet-agent
